"""
NSE Trading MCP Server
=======================
Exposes trading platform data as MCP (Model Context Protocol) tools,
so Claude Desktop / AI agents can query live market data, signals,
and predictions directly via natural language.

Tools exposed:
  - get_market_snapshot   : LTP, VIX, PCR, Max Pain, OI signal
  - get_option_chain      : Full option chain for a symbol+expiry
  - get_ml_prediction     : Latest ML model prediction
  - get_signals           : Recent trading signals from DB
  - get_positions         : Open positions and P&L
  - get_news_sentiment    : Market/symbol sentiment from news
  - run_market_scan       : Trigger a one-shot market scan

Inspired by vendors/nse-mcp/ and vendors/mcp-tradingview/

Run: python core/ai/mcp_server.py
Connect in Claude Desktop: see config/claude_desktop_mcp.json
"""
import sys
import json
import asyncio
from pathlib import Path
from datetime import datetime
from typing import Any, Dict, Optional

ROOT = Path(__file__).parent.parent.parent
sys.path.insert(0, str(ROOT))

from loguru import logger


def _json_safe(obj):
    """Make objects JSON-serializable."""
    if isinstance(obj, datetime):
        return obj.isoformat()
    if hasattr(obj, "__dict__"):
        return obj.__dict__
    return str(obj)


class NseTradingMCPServer:
    """
    Lightweight MCP server for the NSE trading platform.
    Implements the MCP JSON-RPC 2.0 protocol over stdio.
    """

    SERVER_INFO = {
        "name":    "nse-trading",
        "version": "1.0.0",
    }

    TOOLS = [
        {
            "name": "get_market_snapshot",
            "description": "Get live market snapshot: LTP, VIX, PCR, Max Pain, OI signal for a Nifty index.",
            "inputSchema": {
                "type": "object",
                "properties": {
                    "symbol": {"type": "string", "enum": ["NIFTY", "BANKNIFTY", "FINNIFTY"], "default": "NIFTY"},
                },
            },
        },
        {
            "name": "get_option_chain",
            "description": "Fetch the NSE option chain for a symbol. Returns CE/PE OI, IV, LTP for ATM ± 10 strikes.",
            "inputSchema": {
                "type": "object",
                "properties": {
                    "symbol": {"type": "string", "default": "NIFTY"},
                    "expiry": {"type": "string", "description": "Expiry date e.g. '18-Sep-2025' (optional, uses nearest)"},
                },
            },
        },
        {
            "name": "get_ml_prediction",
            "description": "Get ML model prediction (XGBoost+LightGBM) for direction and return forecast.",
            "inputSchema": {
                "type": "object",
                "properties": {
                    "symbol": {"type": "string", "default": "NIFTY"},
                },
            },
        },
        {
            "name": "get_signals",
            "description": "Retrieve recent trading signals generated by the strategy engine.",
            "inputSchema": {
                "type": "object",
                "properties": {
                    "limit": {"type": "integer", "default": 10},
                },
            },
        },
        {
            "name": "get_positions",
            "description": "Get current open positions and unrealized P&L.",
            "inputSchema": {"type": "object", "properties": {}},
        },
        {
            "name": "get_news_sentiment",
            "description": "Get aggregated market or symbol-specific news sentiment.",
            "inputSchema": {
                "type": "object",
                "properties": {
                    "symbol": {"type": "string", "description": "NSE symbol (optional, e.g. RELIANCE). Leave empty for market-wide sentiment."},
                },
            },
        },
        {
            "name": "run_market_scan",
            "description": "Run a one-shot market scan and return strategy signals for all configured indices.",
            "inputSchema": {"type": "object", "properties": {}},
        },
    ]

    # ── Tool handlers ──────────────────────────────────────────────────────────

    def handle_get_market_snapshot(self, symbol: str = "NIFTY") -> Dict:
        from core.data.nse_scraper import get_scraper
        scraper = get_scraper()
        sym_map = {"NIFTY": "NIFTY 50", "BANKNIFTY": "NIFTY BANK", "FINNIFTY": "NIFTY FIN SERVICE"}
        quote   = scraper.get_index_quote(sym_map.get(symbol, symbol)) or {}
        vix     = scraper.get_vix() or 0
        pcr_d   = scraper.get_pcr_data(symbol) or {}
        max_p   = scraper.get_max_pain(symbol) or 0

        return {
            "symbol":    symbol,
            "ltp":       quote.get("ltp", 0),
            "change_pct":quote.get("change_pct", 0),
            "vix":       vix,
            "pcr_oi":    pcr_d.get("pcr_oi", 0),
            "max_pain":  max_p,
            "market_open": scraper.is_market_open(),
            "timestamp": datetime.now().isoformat(),
        }

    def handle_get_option_chain(self, symbol: str = "NIFTY", expiry: Optional[str] = None) -> Dict:
        from core.data.nse_scraper import get_scraper
        records = get_scraper().parse_option_chain(symbol, expiry, strikes_range=10)
        return {
            "symbol":  symbol,
            "expiry":  expiry or "nearest",
            "records": records[:40],   # limit for context window
            "count":   len(records),
        }

    def handle_get_ml_prediction(self, symbol: str = "NIFTY") -> Dict:
        try:
            from core.ml.predictor import get_predictor
            from core.data.historical import fetch_historical, add_indicators
            pr    = get_predictor(symbol)
            ohlcv = fetch_historical(symbol, "5min", days=10)
            if ohlcv.empty or not pr.is_ready():
                return {"error": "Model not trained or no data"}
            ohlcv = add_indicators(ohlcv)
            res   = pr.predict(ohlcv)
            if res is None:
                return {"error": "Prediction failed"}
            return {
                "symbol":           res.symbol,
                "direction":        res.direction,
                "confidence":       res.confidence,
                "signal_strength":  res.signal_strength,
                "prob_up":          res.prob_up,
                "prob_down":        res.prob_down,
                "predicted_return": res.predicted_return,
                "label_5class":     res.label_5class,
                "timestamp":        res.timestamp.isoformat(),
            }
        except Exception as e:
            return {"error": str(e)}

    def handle_get_signals(self, limit: int = 10) -> Dict:
        try:
            from core.data.db import DBManager
            with DBManager() as db:
                sigs = db.get_recent_signals(limit)
            return {
                "signals": [
                    {
                        "strategy":  s.strategy,
                        "symbol":    s.symbol,
                        "direction": s.direction,
                        "price":     s.price,
                        "notes":     s.notes,
                        "timestamp": s.timestamp.isoformat(),
                        "executed":  s.executed,
                    }
                    for s in sigs
                ]
            }
        except Exception as e:
            return {"error": str(e)}

    def handle_get_positions(self) -> Dict:
        try:
            from core.data.db import DBManager
            with DBManager() as db:
                trades = db.get_open_trades()
            return {
                "open_positions": len(trades),
                "positions": [
                    {
                        "symbol":    t.symbol,
                        "direction": t.direction,
                        "entry":     t.entry_price,
                        "qty":       t.quantity,
                        "strategy":  t.strategy,
                    }
                    for t in trades
                ],
            }
        except Exception as e:
            return {"error": str(e)}

    def handle_get_news_sentiment(self, symbol: str = "") -> Dict:
        try:
            from core.news.collector import get_news_collector
            nc = get_news_collector()
            if symbol:
                return nc.get_symbol_sentiment(symbol)
            return nc.get_market_sentiment()
        except Exception as e:
            return {"error": str(e)}

    def handle_run_market_scan(self) -> Dict:
        results = []
        try:
            from core.data.historical import fetch_historical, add_indicators
            from core.strategies.swing.trend_swing import SwingTrendStrategy
            from core.strategies.positional.long_term import LongTermStrategy

            for sym in ["NIFTY", "BANKNIFTY"]:
                data = fetch_historical(sym, "1d", 365)
                if data.empty:
                    continue
                data = add_indicators(data)
                for strat in [SwingTrendStrategy(), LongTermStrategy()]:
                    try:
                        sigs = strat.generate_signals(data, symbol=sym)
                        for s in sigs:
                            results.append({
                                "strategy":  strat.name,
                                "symbol":    sym,
                                "direction": s.direction,
                                "price":     s.price,
                                "notes":     s.notes,
                            })
                    except Exception:
                        pass
        except Exception as e:
            return {"error": str(e)}
        return {"signals": results, "count": len(results), "timestamp": datetime.now().isoformat()}

    # ── MCP JSON-RPC server ────────────────────────────────────────────────────

    def dispatch(self, method: str, params: Dict) -> Any:
        """Dispatch tool call to handler."""
        handlers = {
            "get_market_snapshot":  lambda: self.handle_get_market_snapshot(**params),
            "get_option_chain":     lambda: self.handle_get_option_chain(**params),
            "get_ml_prediction":    lambda: self.handle_get_ml_prediction(**params),
            "get_signals":          lambda: self.handle_get_signals(**params),
            "get_positions":        lambda: self.handle_get_positions(),
            "get_news_sentiment":   lambda: self.handle_get_news_sentiment(**params),
            "run_market_scan":      lambda: self.handle_run_market_scan(),
        }
        handler = handlers.get(method)
        if not handler:
            raise ValueError(f"Unknown tool: {method}")
        return handler()

    def run(self):
        """Run MCP server over stdio."""
        logger.info("NSE Trading MCP Server starting (stdio transport)...")
        while True:
            try:
                line = sys.stdin.readline()
                if not line:
                    break
                request = json.loads(line.strip())
                rpc_id  = request.get("id")
                method  = request.get("method", "")
                params  = request.get("params", {})

                if method == "initialize":
                    response = {
                        "jsonrpc": "2.0", "id": rpc_id,
                        "result": {
                            "protocolVersion": "2024-11-05",
                            "capabilities": {"tools": {}},
                            "serverInfo": self.SERVER_INFO,
                        },
                    }
                elif method == "tools/list":
                    response = {
                        "jsonrpc": "2.0", "id": rpc_id,
                        "result": {"tools": self.TOOLS},
                    }
                elif method == "tools/call":
                    tool_name   = params.get("name", "")
                    tool_params = params.get("arguments", {})
                    try:
                        result = self.dispatch(tool_name, tool_params)
                        response = {
                            "jsonrpc": "2.0", "id": rpc_id,
                            "result": {
                                "content": [{
                                    "type": "text",
                                    "text": json.dumps(result, default=_json_safe, indent=2),
                                }]
                            },
                        }
                    except Exception as e:
                        response = {
                            "jsonrpc": "2.0", "id": rpc_id,
                            "error": {"code": -32000, "message": str(e)},
                        }
                else:
                    response = {
                        "jsonrpc": "2.0", "id": rpc_id,
                        "error": {"code": -32601, "message": f"Method not found: {method}"},
                    }

                print(json.dumps(response), flush=True)

            except json.JSONDecodeError:
                pass
            except KeyboardInterrupt:
                break
            except Exception as e:
                logger.error(f"MCP server error: {e}")


if __name__ == "__main__":
    NseTradingMCPServer().run()
