"""
Base Strategy class - all strategies inherit from this.
"""
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import datetime
from typing import Optional, List, Dict, Any

import pandas as pd
from loguru import logger

from core.brokers.base import BaseBroker


@dataclass
class TradeSignal:
    """A signal generated by a strategy."""
    strategy: str
    symbol: str
    direction: str           # BUY | SELL | NEUTRAL
    signal_type: str         # ENTRY | EXIT | SL | TARGET
    price: float = 0.0
    target: float = 0.0
    stop_loss: float = 0.0
    quantity: int = 0
    confidence: float = 0.0  # 0.0 - 1.0
    notes: str = ""
    timestamp: datetime = field(default_factory=datetime.now)
    meta: Dict[str, Any] = field(default_factory=dict)


class BaseStrategy(ABC):
    """
    All strategies must implement generate_signals().
    Optional: on_bar() for bar-by-bar processing during backtest.
    """

    name: str = "base"
    description: str = ""

    def __init__(self, broker: Optional[BaseBroker] = None, config: Dict = None):
        self.broker = broker
        self.config = config or {}
        self.signals: List[TradeSignal] = []
        self.enabled = True

    @abstractmethod
    def generate_signals(self, data: pd.DataFrame, **kwargs) -> List[TradeSignal]:
        """Generate trading signals from market data."""
        ...

    def execute_signals(self, signals: List[TradeSignal]) -> List[Dict]:
        """Execute signals via broker (if broker is set)."""
        results = []
        if not self.broker:
            logger.warning(f"[{self.name}] No broker attached, signals not executed")
            return results
        for sig in signals:
            if sig.signal_type == "ENTRY" and sig.direction in ("BUY", "SELL"):
                try:
                    if sig.direction == "BUY":
                        resp = self.broker.buy(sig.symbol, sig.quantity, tag=self.name)
                    else:
                        resp = self.broker.sell(sig.symbol, sig.quantity, tag=self.name)
                    results.append({"signal": sig, "response": resp})
                    logger.info(f"[{self.name}] Executed {sig.direction} {sig.symbol}")
                except Exception as e:
                    logger.error(f"[{self.name}] Execution error: {e}")
        return results

    def on_bar(self, bar: Dict) -> Optional[TradeSignal]:
        """Called for each new bar during live trading. Override if needed."""
        return None

    def __repr__(self):
        return f"<Strategy: {self.name}>"
