"""
Database manager using SQLAlchemy + SQLite.
Stores: OI snapshots, OHLC bars, trades, signals, positions.
"""
import json
from datetime import datetime
from pathlib import Path
from typing import Optional, List

from sqlalchemy import (
    create_engine, Column, Integer, Float, String,
    DateTime, Boolean, Text, Index, event
)
from sqlalchemy.orm import DeclarativeBase, sessionmaker, Session
from sqlalchemy.pool import StaticPool
from loguru import logger

ROOT_DIR = Path(__file__).parent.parent.parent
DB_PATH = ROOT_DIR / "data" / "db" / "trading.db"
DB_PATH.parent.mkdir(parents=True, exist_ok=True)

engine = create_engine(
    f"sqlite:///{DB_PATH}",
    connect_args={"check_same_thread": False},
    poolclass=StaticPool,
)

# Enable WAL mode for better concurrent reads
@event.listens_for(engine, "connect")
def set_sqlite_pragma(dbapi_conn, _):
    cursor = dbapi_conn.cursor()
    cursor.execute("PRAGMA journal_mode=WAL")
    cursor.execute("PRAGMA synchronous=NORMAL")
    cursor.execute("PRAGMA cache_size=10000")
    cursor.close()

SessionLocal = sessionmaker(bind=engine, autoflush=False, autocommit=False)


class Base(DeclarativeBase):
    pass


# ---- Models ----------------------------------------------------------

class OISnapshot(Base):
    """Option chain OI snapshot every 5 minutes."""
    __tablename__ = "oi_snapshots"

    id = Column(Integer, primary_key=True, autoincrement=True)
    timestamp = Column(DateTime, nullable=False, index=True)
    symbol = Column(String(20), nullable=False, index=True)
    expiry = Column(String(20), nullable=False)
    strike = Column(Float, nullable=False)
    option_type = Column(String(2), nullable=False)   # CE | PE
    oi = Column(Float, default=0)
    oi_change = Column(Float, default=0)
    volume = Column(Float, default=0)
    ltp = Column(Float, default=0)
    iv = Column(Float, default=0)
    delta = Column(Float, default=0)
    theta = Column(Float, default=0)
    vega = Column(Float, default=0)

    __table_args__ = (
        Index("ix_oi_snap_sym_exp_time", "symbol", "expiry", "timestamp"),
    )


class OHLCBar(Base):
    """OHLCV bars for indices and stocks."""
    __tablename__ = "ohlc_bars"

    id = Column(Integer, primary_key=True, autoincrement=True)
    timestamp = Column(DateTime, nullable=False, index=True)
    symbol = Column(String(30), nullable=False, index=True)
    timeframe = Column(String(10), nullable=False)   # 1min, 5min, 15min, 1d, 1wk
    open = Column(Float)
    high = Column(Float)
    low = Column(Float)
    close = Column(Float)
    volume = Column(Float)

    __table_args__ = (
        Index("ix_ohlc_sym_tf_time", "symbol", "timeframe", "timestamp"),
    )


class Signal(Base):
    """Trading signals generated by strategies."""
    __tablename__ = "signals"

    id = Column(Integer, primary_key=True, autoincrement=True)
    timestamp = Column(DateTime, nullable=False, default=datetime.utcnow)
    strategy = Column(String(50), nullable=False)
    symbol = Column(String(30), nullable=False)
    direction = Column(String(10))    # BUY | SELL | NEUTRAL
    signal_type = Column(String(20))  # ENTRY | EXIT | SL | TARGET
    price = Column(Float)
    target = Column(Float)
    stop_loss = Column(Float)
    notes = Column(Text)
    executed = Column(Boolean, default=False)


class Trade(Base):
    """Executed trades (both paper and live)."""
    __tablename__ = "trades"

    id = Column(Integer, primary_key=True, autoincrement=True)
    trade_id = Column(String(50), unique=True)
    broker = Column(String(20), default="paper")
    strategy = Column(String(50))
    symbol = Column(String(30), nullable=False)
    trade_type = Column(String(10))    # BUY | SELL
    quantity = Column(Integer)
    entry_price = Column(Float)
    exit_price = Column(Float)
    entry_time = Column(DateTime)
    exit_time = Column(DateTime)
    pnl = Column(Float, default=0)
    pnl_pct = Column(Float, default=0)
    brokerage = Column(Float, default=0)
    status = Column(String(20), default="OPEN")   # OPEN | CLOSED | SL_HIT | TARGET_HIT
    notes = Column(Text)
    raw_data = Column(Text)   # JSON for extra fields


class Position(Base):
    """Current open positions."""
    __tablename__ = "positions"

    id = Column(Integer, primary_key=True, autoincrement=True)
    strategy = Column(String(50))
    symbol = Column(String(30), nullable=False)
    quantity = Column(Integer)
    avg_price = Column(Float)
    current_price = Column(Float)
    unrealized_pnl = Column(Float, default=0)
    entry_time = Column(DateTime)
    stop_loss = Column(Float)
    target = Column(Float)
    broker = Column(String(20), default="paper")
    notes = Column(Text)


class DailyPnL(Base):
    """Daily P&L summary."""
    __tablename__ = "daily_pnl"

    id = Column(Integer, primary_key=True, autoincrement=True)
    date = Column(String(12), unique=True, nullable=False)
    realized_pnl = Column(Float, default=0)
    unrealized_pnl = Column(Float, default=0)
    total_trades = Column(Integer, default=0)
    winning_trades = Column(Integer, default=0)
    losing_trades = Column(Integer, default=0)
    gross_pnl = Column(Float, default=0)
    brokerage = Column(Float, default=0)
    net_pnl = Column(Float, default=0)


class InstitutionalSnapshot(Base):
    """Daily FII/DII participant-wise derivatives positioning."""
    __tablename__ = "institutional_snapshots"

    id = Column(Integer, primary_key=True, autoincrement=True)
    date = Column(String(12), nullable=False, index=True)
    client_type = Column(String(10), nullable=False)   # FII | DII | PRO | CLI

    # Index futures
    fut_index_long  = Column(Float, default=0)
    fut_index_short = Column(Float, default=0)
    fut_index_net   = Column(Float, default=0)

    # Stock futures
    fut_stock_long  = Column(Float, default=0)
    fut_stock_short = Column(Float, default=0)

    # Index calls
    opt_idx_call_long  = Column(Float, default=0)
    opt_idx_call_short = Column(Float, default=0)
    opt_idx_call_net   = Column(Float, default=0)

    # Index puts
    opt_idx_put_long   = Column(Float, default=0)
    opt_idx_put_short  = Column(Float, default=0)
    opt_idx_put_net    = Column(Float, default=0)

    # Stock options
    opt_stk_call_long  = Column(Float, default=0)
    opt_stk_call_short = Column(Float, default=0)
    opt_stk_put_long   = Column(Float, default=0)
    opt_stk_put_short  = Column(Float, default=0)

    # Totals
    total_long  = Column(Float, default=0)
    total_short = Column(Float, default=0)

    # Derived bias scores
    fut_bias  = Column(Float, default=0)
    call_bias = Column(Float, default=0)
    put_bias  = Column(Float, default=0)

    # Cash equity (for FII/DII rows only)
    cash_buy  = Column(Float, default=0)
    cash_sell = Column(Float, default=0)
    cash_net  = Column(Float, default=0)

    # FII regime (only for FII row)
    regime    = Column(String(30), default="")
    composite = Column(Float, default=0)

    __table_args__ = (
        Index("ix_inst_date_client", "date", "client_type"),
    )


# ---- Init ------------------------------------------------------------

def init_db():
    Base.metadata.create_all(bind=engine)
    logger.info(f"Database initialized at {DB_PATH}")


def get_db() -> Session:
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()


# ---- Helper functions ------------------------------------------------

class DBManager:
    def __init__(self):
        self.session: Session = SessionLocal()

    def close(self):
        self.session.close()

    def __enter__(self):
        return self

    def __exit__(self, *args):
        self.close()

    # OI Snapshots
    def save_oi_snapshot(self, snapshots: List[dict]):
        try:
            for snap in snapshots:
                obj = OISnapshot(**snap)
                self.session.add(obj)
            self.session.commit()
        except Exception as e:
            self.session.rollback()
            logger.error(f"Error saving OI snapshot: {e}")

    def get_oi_history(self, symbol: str, expiry: str, strike: float,
                       option_type: str, limit: int = 100) -> List[OISnapshot]:
        return (
            self.session.query(OISnapshot)
            .filter_by(symbol=symbol, expiry=expiry, strike=strike, option_type=option_type)
            .order_by(OISnapshot.timestamp.desc())
            .limit(limit)
            .all()
        )

    # OHLC Bars
    def save_ohlc(self, bars: List[dict]):
        try:
            for bar in bars:
                # Upsert by checking existing
                existing = (
                    self.session.query(OHLCBar)
                    .filter_by(
                        symbol=bar["symbol"],
                        timeframe=bar["timeframe"],
                        timestamp=bar["timestamp"]
                    )
                    .first()
                )
                if existing:
                    for k, v in bar.items():
                        setattr(existing, k, v)
                else:
                    self.session.add(OHLCBar(**bar))
            self.session.commit()
        except Exception as e:
            self.session.rollback()
            logger.error(f"Error saving OHLC: {e}")

    def get_ohlc(self, symbol: str, timeframe: str, limit: int = 500) -> List[OHLCBar]:
        return (
            self.session.query(OHLCBar)
            .filter_by(symbol=symbol, timeframe=timeframe)
            .order_by(OHLCBar.timestamp.asc())
            .limit(limit)
            .all()
        )

    # Signals
    def save_signal(self, signal: dict) -> Signal:
        try:
            obj = Signal(**signal)
            self.session.add(obj)
            self.session.commit()
            self.session.refresh(obj)
            return obj
        except Exception as e:
            self.session.rollback()
            logger.error(f"Error saving signal: {e}")

    def get_recent_signals(self, limit: int = 50) -> List[Signal]:
        return (
            self.session.query(Signal)
            .order_by(Signal.timestamp.desc())
            .limit(limit)
            .all()
        )

    # Trades
    def save_trade(self, trade: dict) -> Trade:
        try:
            obj = Trade(**trade)
            self.session.add(obj)
            self.session.commit()
            self.session.refresh(obj)
            return obj
        except Exception as e:
            self.session.rollback()
            logger.error(f"Error saving trade: {e}")

    def get_open_trades(self) -> List[Trade]:
        return (
            self.session.query(Trade)
            .filter_by(status="OPEN")
            .all()
        )

    def get_all_trades(self, limit: int = 200) -> List[Trade]:
        return (
            self.session.query(Trade)
            .order_by(Trade.entry_time.desc())
            .limit(limit)
            .all()
        )

    def update_trade(self, trade_id: str, updates: dict):
        try:
            trade = self.session.query(Trade).filter_by(trade_id=trade_id).first()
            if trade:
                for k, v in updates.items():
                    setattr(trade, k, v)
                self.session.commit()
        except Exception as e:
            self.session.rollback()
            logger.error(f"Error updating trade: {e}")

    # Daily P&L
    def upsert_daily_pnl(self, date_str: str, updates: dict):
        try:
            obj = self.session.query(DailyPnL).filter_by(date=date_str).first()
            if obj:
                for k, v in updates.items():
                    setattr(obj, k, v)
            else:
                obj = DailyPnL(date=date_str, **updates)
                self.session.add(obj)
            self.session.commit()
        except Exception as e:
            self.session.rollback()
            logger.error(f"Error updating daily PnL: {e}")

    def get_daily_pnl(self, days: int = 30) -> List[DailyPnL]:
        return (
            self.session.query(DailyPnL)
            .order_by(DailyPnL.date.desc())
            .limit(days)
            .all()
        )

    # Institutional Snapshots
    def save_institutional_snapshot(self, rows: List[dict]):
        """Upsert participant-wise snapshot rows (one per client_type per date)."""
        try:
            for row in rows:
                existing = (
                    self.session.query(InstitutionalSnapshot)
                    .filter_by(date=row.get("date"), client_type=row.get("client_type", ""))
                    .first()
                )
                allowed = {c.name for c in InstitutionalSnapshot.__table__.columns}
                filtered = {k: v for k, v in row.items() if k in allowed}
                if existing:
                    for k, v in filtered.items():
                        setattr(existing, k, v)
                else:
                    self.session.add(InstitutionalSnapshot(**filtered))
            self.session.commit()
        except Exception as e:
            self.session.rollback()
            logger.error(f"Error saving institutional snapshot: {e}")

    def get_institutional_history(self, client_type: str = "FII",
                                  days: int = 30) -> List[InstitutionalSnapshot]:
        return (
            self.session.query(InstitutionalSnapshot)
            .filter_by(client_type=client_type)
            .order_by(InstitutionalSnapshot.date.desc())
            .limit(days)
            .all()
        )

    def get_latest_institutional(self, client_type: str = "FII") -> Optional[InstitutionalSnapshot]:
        return (
            self.session.query(InstitutionalSnapshot)
            .filter_by(client_type=client_type)
            .order_by(InstitutionalSnapshot.date.desc())
            .first()
        )
